# See https://github.com/lowlighter/metrics for documentation

name: Metrics
on:
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        uses: lowlighter/metrics@latest
        with:
          user: AzharRizky
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}

      - name: 🦑 Personal metrics (achievements)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          user: kevinalfito69
          plugin_achievements: yes
          plugin_achievements_secrets: yes     
          plugin_achievements_display: compact 
          filename: metrics.plugin.achivements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}

     

      - name: 🦑 Personal metrics (starred)
        uses: lowlighter/metrics@master
        with:
          user: kevinalfito69
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}

      - name: 🧑‍🤝‍🧑 People plugin (followers)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          user: kevinalfito69
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_identicons: yes
          plugin_people_types: followers
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}

      - name: 🈷️ Languages plugin (detailed)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          user: kevinalfito69
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, smarty, tex, jupyter notebook
          plugin_languages_details: bytes-size, percentage
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
